<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>4man score</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="css/tablesorter/theme.bootstrap.css" rel="stylesheet" media="screen">
    <style>
        body {padding-top: 65px;}
    </style>

    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/tablesorter/jquery.tablesorter.min.js"></script>
    <script src="js/tablesorter/jquery.tablesorter.widgets.min.js"></script>
    <script>
        $(function() {
            $('table#points').tablesorter({
                theme : 'bootstrap',
                sortList: [[1,1]],
                headerTemplate: '{content} {icon}',
                widgets    : ['zebra','columns', 'uitheme']
            });
        });
    </script>
</head>
<body>
