<?php $db = Services::getDBConnection() ?>
<?php $result = $db->query('SELECT * FROM points'); ?>
<div class="container">
    <table id="points">
        <thead>
        <tr>
            <th>Фамилия</th>
            <th>Очков</th>
            <th>Доступно</th>
            <th>Потрачено</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($result as $row) : ?>
            <tr>
                <td><?php echo $row['last_name'] ?></td>
                <td><?php echo $row['points'] ?></td>
                <td><?php echo $row['used'] ?></td>
                <td><?php echo $row['available'] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>