<?php $db = Services::getDBConnection() ?>
<?php $users = $db->query('SELECT * FROM points') ?>
<script>
    $(function() {
        $('table#points').tablesorter({
            theme : 'bootstrap',
            sortList: [[3,1]],
            headerTemplate: '{content} {icon}',
            widgets    : ['zebra','columns', 'uitheme']
        });
    });
</script>
<div class="container">
    <table id="points">
        <thead>
        <tr>
            <th>Фамилия</th>
            <th>Плюс</th>
            <th>Минус</th>
            <th>Баланс</th>
            <th>Потрачено</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($users as $row) : ?>
            <tr>
                <td><?php echo $row['last_name'] ?></td>
                <td><?php echo $row['positive'] ?></td>
                <td><?php echo $row['negative'] ?></td>
                <td><?php echo $row['balance'] ?></td>
                <td><?php echo $row['spend'] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>