<?php $mode = !empty($_GET['mode']) ? $_GET['mode'] : '' ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Points manager</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="css/tablesorter/theme.bootstrap.css" rel="stylesheet" media="screen">
    <style>
        body {padding-top: 65px;}
    </style>

    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/tablesorter/jquery.tablesorter.min.js"></script>
    <script src="js/tablesorter/jquery.tablesorter.widgets.min.js"></script>
</head>
<body>
<div class="container">
    <ul class="nav nav-pills">
        <li <?php if($mode == ''): ?>class="active"<?php endif; ?>><a href="index.php">Просмотр</a></li>
        <li <?php if($mode == 'points_manage'): ?>class="active"<?php endif; ?>><a href="index.php?mode=points_manage">Управление</a></li>
    </ul>