<?php $mode = !empty($_GET['mode']) ? $_GET['mode'] : '' ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <?php
        $titles = array(
            '5b9e92aff51dc303877ff986083f5e3f',
            '958c007d490c94eb6764f3efd89ad4a8',
            '42f0d762a8587dbb364ddde4f6a4fc6d'
        )
    ?>
    <title><?php echo $titles[rand(0, 2)] ?></title>
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="css/tablesorter/theme.bootstrap.css" rel="stylesheet" media="screen">
    <style>
        body {padding-top: 10px;}
    </style>
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/tablesorter/jquery.tablesorter.min.js"></script>
    <script src="js/tablesorter/jquery.tablesorter.widgets.min.js"></script>
</head>
<body>
<div class="container">
    <div class="pagination-centered">
        <img class="text-center" width="150" src="img/evolution/<?php echo rand(1, 8) ?>.jpg" />
    </div>
    <ul class="nav nav-pills">
        <li <?php if($mode == ''): ?>class="active"<?php endif; ?>><a href="/">Очки</a></li>
        <li <?php if($mode == 'history'): ?>class="active"<?php endif; ?>><a href="index.php?mode=history">История</a></li>
        <li <?php if($mode == 'market'): ?>class="active"<?php endif; ?>><a href="index.php?mode=market">Маркет</a></li>
        <li <?php if($mode == 'plans'): ?>class="active"<?php endif; ?>><a href="index.php?mode=plans">План</a></li>
        <li <?php if($mode == 'links'): ?>class="active"<?php endif; ?>><a href="index.php?mode=links">Полезные ссылки</a></li>
    </ul>