<?php
    $db = Services::getDBConnection();
    $links = $db->query(
        'SELECT lg.name AS group_name, l.title, l.href, l.created
           FROM links AS l
           INNER JOIN link_groups AS lg ON l.group_id = lg.group_id
         ORDER BY group_name, created DESC'
    );
    foreach ($links as $link) {
        $out[$link['group_name']][] = array('title' => $link['title'], 'href' => $link['href'], 'created' => $link['created']);
    }
?>
<div class="container">
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Группа</th>
            <th>Ссылка</th>
            <th>Дата</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($out as $key => $items): ?>
            <tr>
                <td rowspan="<?php echo count($items) ?>"><?php echo $key ?></td>
            <?php $last_key = end(array_keys($items)) ?>
            <?php foreach ($items as $key => $item): ?>
                <td><a href="<?php echo $item['href'] ?>"><?php echo $item['title'] ?></a></td>
                <td><?php echo $item['created'] ?></td>
            <?php if ($key !== $last_key): ?>
            </tr>
            <tr>
            <?php endif; ?>
            <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>