<?php $db = Services::getDBConnection() ?>
<?php $users = $db->query('SELECT user_id, last_name FROM points') ?>

<form action="index.php?mode=points_manage_save" method="post">
    <input name="mode" type="hidden" value="points_manage_save" />
    <fieldset>
        <legend>Сохранить очки</legend>
        <?php if(isset($_GET['save']) && $_GET['save']): ?>
            <p class="text-success">Данные успешно сохранены.</p>
        <?php endif; ?>
        <label for="user_id">Фамилия:</label>
        <select name="user_id" id="user_id" required>
            <option value=""></option>
        <?php foreach($users as $user) : ?>
            <option value="<?php echo $user['user_id'] ?>"><?php echo $user['last_name'] ?></option>
        <?php endforeach; ?>
        </select>
        <label for="points">Очки:</label>
        <input type="text" name="points" id="points" required/>
        <label for="comment">Комментарий:</label>
        <textarea name="comment" id="comment" cols="30" rows="10" required></textarea>
        <label for="type_id">Тип:</label>
        <select name="type_id" id="type_id" required>
            <option value="<?php echo POINTS_BALANCE ?>" selected>Баланс</option>
            <option value="<?php echo POINTS_SPEND ?>">Потрачено</option>
        </select>
        <br>
        <input type="submit" value="Сохранить"/>
    </fieldset>
</form>