<div class="container">
    <ul>
        <li>Не отвечаете на вопрос: <i class="text-error">-1</i></li>
        <li>Обманываете: <i class="text-error">-50</i></li>
        <li>Что-то мне не нравится: <i class="text-error">-на_месте_разберемся</i></li>
        <li>Коммит по заданию на github: <i class="text-info">+1</i></li>
        <li>Очередные 100 очков на SO: <i class="text-info">+5</i></li>
    </ul>
    <p>Вы можете придумать как использовать очки, я назначу за это количество баллов.</p>
    <p class="blood-image">И помните, что все правила написаны <span class="blood">кровью!</span></p>
</div>